<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #628ab7;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 70px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>To Do List</h1>
<br>
<form action="/homepage/addTask" method="post">
    <input type="text" id="lname" name="task">
    <input type="submit" value="Add">
</form>
<br>
<?php foreach ($tasks as $task) : ?>
    <p><?= $task['task'] ?><button>✎</button><a href='/completeATask/<?= $task['id'] ?>'>✔</a></p>
<?php endforeach; ?>
<a href="/completedTasks">See Completed Tasks</a>
</body>
</html>
